// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AuthController from "./auth_controller"
import UsersFormNewController from "./users_form_new_controller"

application.register("auth", AuthController)
application.register("users_form_new", UsersFormNewController)
